### PR TITLE
Add support for neovim

### PR DESCRIPTION
**Pull request by jceb**
I'm not 100% sure about whether the argument in this line needs escaping of double quotes: https://github.com/maralla/completor.vim/compare/master...jceb:nvim-support?expand=1#diff-9265ec59ebd21ebdd8b777e5f778cf8cR59

### CODE REVIEW

**Comment by jceb** [comment]
Would fix issue #26

**Comment by prabirshrestha** [comment]
+1.

(seems like need rebasing too)

**Comment by gaving** [comment]
👍

**Comment by DanielFGray** [comment]
this doesn't work for me, neovim is throwing `E486: Pattern not found: trigger(a`

**Comment by prabirshrestha** [comment]
landed up writing my own that works in vim8 and neovim.

https://github.com/prabirshrestha/asyncomplete.vim

**Comment by megalithic** [comment]
So, I take it neovim support is somewhat (or totally abandoned) for this plugin specifically?

**Comment by maralla** [comment]
I carefully rewrites the support for neovim in #77. Thanks for this pr. Now I close this pr in favour of the new implementation.

**Pull request closed without merging**
