### PR TITLE
Add cwd option for job

### PR DESCRIPTION
**Pull request by damnever**
~~Or, make all options configurable?~~

### CODE REVIEW

**Comment by damnever** [comment]
The PR is made for this reason: `job_start('cd /bin && ls', ...)` is not working, and I think `cwd` option is better than `job_start('sh -c "cd /bin && ls"', ...)`. @maralla

**Comment by maralla** [comment]
So what is the problem the changes solved for completor?

**Comment by damnever** [comment]
> Async completion framework made ease.

**Comment by damnever** [comment]
I am writing a plugin based on completor.vim, and I also need to custom the `env` option. I think that making most of those options configurable is acceptable for the framework, anyway, I am currently using the `sh -c` style, so...

**Pull request closed without merging**
